# Generated by Django 4.2.11 on 2024-04-12 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.DeleteModel(
            name='UserConnection',
        ),
    ]
