# Generated by Django 4.2.11 on 2024-04-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0003_alter_user_managers_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
