# Generated by Django 4.2.11 on 2024-04-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0004_remove_user_groups_remove_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
